version: '3.3'

services:
  app:
    image: node:16.14-alpine
    tty: true
    stdin_open: true
    container_name: jurishand-app
    working_dir: /app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      PORT: '3000'
      HOST: jurishand-app
    volumes:
      - .:/app
  
  db:
    image: mysql:8.0.23
    container_name: jurishand-app-db
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
